/*
** ###################################################################
**     This code is generated by the Device Initialization Tool.
**     It is overwritten during code generation.
**     USER MODIFICATION ARE PRESERVED ONLY INSIDE INTERRUPT SERVICE ROUTINES
**     OR EXPLICITLY MARKED SECTIONS
**
**     Project     : Serial_01
**     Processor   : MC9S08QE8CPG
**     Version     : Component 01.003, Driver 01.08, CPU db: 3.00.048
**     Datasheet   : MC9S08QE8RM Rev. 3 1/2008
**     Date/Time   : 2013-05-04, 01:05, # CodeGen: 0
**     Abstract    :
**         This module contains device initialization code 
**         for selected on-chip peripherals.
**     Contents    :
**         Function "MCU_init" initializes selected peripherals
**
**     Copyright : 1997 - 2011 Freescale Semiconductor, Inc. All Rights Reserved.
**     
**     http      : www.freescale.com
**     mail      : support@freescale.com
** ###################################################################
*/

/* MODULE MCUinit */

#include <mc9s08qe8.h>                 /* I/O map for MC9S08QE8CPG */
#include "MCUinit.h"

/* Standard ANSI C types */
#ifndef int8_t
typedef signed char int8_t;
#endif
#ifndef int16_t
typedef signed int int16_t;
#endif
#ifndef int32_t
typedef signed long int int32_t;
#endif

#ifndef uint8_t
typedef unsigned char uint8_t;
#endif
#ifndef uint16_t
typedef unsigned int uint16_t;
#endif
#ifndef uint32_t
typedef unsigned long int uint32_t;
#endif

/* User declarations and definitions */
/*   Code, declarations and definitions here will be preserved during code generation */
/* End of user declarations and definitions */


/*
** ===================================================================
**     Method      :  MCU_init (component MC9S08QE8_16)
**
**     Description :
**         Device initialization code for selected peripherals.
** ===================================================================
*/
void MCU_init(void)
{
  asm SEI;                             /* Disable interrupts */
  /* ### MC9S08QE8_16 "Cpu" init code ... */
  /*  PE initialization code after reset */
  /* Common initialization of the write once registers */
  /* SOPT1: COPE=0,COPT=1,STOPE=0,BKGDPE=1,RSTPE=0 */
  SOPT1 = 66U;                                      
  /* SOPT2: COPCLKS=0,TPM2CH2PS=0,TPM1CH2PS=0,ACIC2=0,IICPS=0,ACIC1=0 */
  SOPT2 = 0U;                                      
  /* SPMSC1: LVDF=0,LVDACK=0,LVDIE=0,LVDRE=1,LVDSE=1,LVDE=1,BGBE=0 */
  SPMSC1 = 28U;                                      
  /* SPMSC2: LPR=0,LPRS=0,LPWUI=0,PPDF=0,PPDACK=0,PPDE=1,PPDC=0 */
  SPMSC2 = 2U;                                      
  /* SPMSC3: LVWIE=0 */
  SPMSC3 &= (unsigned char)~(unsigned char)8U;                     
  /*  System clock initialization */
  /*lint -save  -e923 Disable MISRA rule (11.3) checking. */
  if (*(unsigned char*far)65455U != 255U) { /* Test if the device trim value is stored on the specified address */
    ICSTRM = *(unsigned char*far)65455U; /* Initialize ICSTRM register from a non volatile memory */
    ICSSC = (unsigned char)((*(unsigned char*far)65454U) & (unsigned char)1U); /* Initialize ICSSC register from a non volatile memory */
  }
  /*lint -restore Enable MISRA rule (11.3) checking. */
  /* ICSC1: CLKS=0,RDIV=0,IREFS=1,IRCLKEN=0,IREFSTEN=0 */
  ICSC1 = 4U;                          /* Initialization of the ICS control register 1 */
  /* ICSC2: BDIV=0,RANGE=0,HGO=0,LP=0,EREFS=0,ERCLKEN=0,EREFSTEN=0 */
  ICSC2 = 0U;                          /* Initialization of the ICS control register 2 */
  while(ICSSC_IREFST == 0U) {          /* Wait until the source of reference clock is internal clock */
   {asm sta SRS;}                      /* Reset watchdog counter */
  }
  /* ICSSC: DRST_DRS=0,DMX32=1 */
  ICSSC = (ICSSC & (unsigned char)~(unsigned char)192U) | (unsigned char)32U; /* Initialization of the ICS status and control */
  while((ICSSC & 192U) != 0U) {        /* Wait until the FLL switches to Low range DCO mode */
   {asm sta SRS;}                      /* Reset watchdog counter */
  }

  /* SCGC1: TPM2=1,TPM1=1,ADC=1,IIC=1,SCI=1 */
  SCGC1 = 255U;                                      
  /* SCGC2: DBG=1,FLS=1,IRQ=1,KBI=1,ACMP=1,RTC=1,SPI=1 */
  SCGC2 = 255U;                                      
  /* Common initialization of the CPU registers */
  /* PTASE: PTASE4=0,PTASE3=0,PTASE2=0,PTASE1=0,PTASE0=0 */
  PTASE &= (unsigned char)~(unsigned char)31U;                     
  /* PTBSE: PTBSE7=0,PTBSE6=0,PTBSE5=0,PTBSE4=0,PTBSE3=0,PTBSE2=0,PTBSE1=0,PTBSE0=0 */
  PTBSE = 0U;                                      
  /* PTADS: PTADS7=0,PTADS6=0,PTADS5=0,PTADS4=0,PTADS3=1,PTADS2=1,PTADS1=1,PTADS0=1 */
  PTADS = 15U;                                      
  /* PTBDS: PTBDS7=0,PTBDS6=0,PTBDS5=0,PTBDS4=0,PTBDS3=0,PTBDS2=0,PTBDS1=0,PTBDS0=0 */
  PTBDS = 0U;                                      
  /* ### Init_COP init code */
  SRS = 255U;                          /* Clear WatchDog counter */
  /* ### Init_GPIO init code */
  /* PTAD: PTAD3=1,PTAD2=1,PTAD1=1,PTAD0=1 */
  PTAD |= (unsigned char)15U;                      
  /* PTADD: PTADD3=1,PTADD2=1,PTADD1=1,PTADD0=1 */
  PTADD |= (unsigned char)15U;                      
  /* ### Init_TPM init code */
  /* TPM1SC: TOF=0,TOIE=0,CPWMS=0,CLKSB=0,CLKSA=0,PS2=0,PS1=0,PS0=0 */
  TPM1SC = 0U;                         /* Stop and reset counter */
  TPM1MOD = 9965U;                     /* Period value setting */
  (void)(TPM1SC == 0U);                /* Overflow int. flag clearing (first part) */
  /* TPM1SC: TOF=0,TOIE=1,CPWMS=0,CLKSB=0,CLKSA=1,PS2=0,PS1=0,PS0=0 */
  TPM1SC = 72U;                        /* Int. flag clearing (2nd part) and timer control register setting */
  /* ### Init_GPIO init code */
  /* PTBD: PTBD7=0,PTBD6=0,PTBD5=0,PTBD4=0,PTBD3=0,PTBD2=0,PTBD1=0,PTBD0=0 */
  PTBD = 0U;                                      
  /* PTBDD: PTBDD7=1,PTBDD6=1,PTBDD5=1,PTBDD4=1,PTBDD3=1,PTBDD2=1,PTBDD1=1,PTBDD0=1 */
  PTBDD = 255U;                                      
  /* ### */

} /*MCU_init*/





/* END MCUinit */

/*
** ###################################################################
**
**     This file was created by Processor Expert 5.3 [05.01]
**     for the Freescale HCS08 series of microcontrollers.
**
** ###################################################################
*/
